import { ureticiNiyeti, musteriNiyeti, zamanAraligi, sadelestir } from "../panel-uretici/src/api/ayristirici.js";
const musteriler = [
  { id: "MST-1", ad: "Ahmet Yılmaz", il: "Adana", ilce: "Seyhan" },
  { id: "MST-2", ad: "Ayşe Demir", il: "İzmir", ilce: "Bornova" },
  { id: "MST-3", ad: "Güneş Enerji Ltd. Şti.", il: "Konya", ilce: "Selçuklu" },
];
let hata = 0;
const dene = (f, soru, bek, ek) => {
  const r = f(soru, { musteriler });
  const n = r?.niyet ?? null;
  const ok = n === bek && (!ek || ek(r));
  if (!ok) hata++;
  console.log(`${ok ? "✓" : "✗"} ${soru.padEnd(62)} → ${n}${r?.alan && r.alan !== "hepsi" ? " [" + r.alan + "]" : ""}${r?.zaman ? " (" + r.zaman.ad + ")" : ""}${r?.il ? " {" + r.il + "}" : ""}${r?.musteriler ? " <" + r.musteriler.map((m) => m.ad).join(",") + ">" : ""}${ok ? "" : "   BEKLENEN " + bek}`);
};
console.log("── ÜRETİCİ");
const U = (s, b, e) => dene(ureticiNiyeti, s, b, e);
U("dostum bana bugünkü kayıt olan kullanıcıların bilgisini ver", "musteri_kayit", (r) => r.zaman.ad === "bugün");
U("bu hafta kaç yeni müşteri geldi", "musteri_kayit", (r) => r.zaman.ad === "bu hafta");
U("dün kaydolanlar kimler", "musteri_kayit", (r) => r.zaman.ad === "dün");
U("son 3 günde üye olanlar", "musteri_kayit", (r) => r.zaman.ad === "son 3 gün");
U("yeni müşteriler", "musteri_kayit");
U("1 müşterinin adres bilgisini bul", "musteri_listesi", (r) => r.alan === "adres");
U("Müşterilerin adres bilgisi nedir?", "musteri_listesi", (r) => r.alan === "adres");
U("müşteri telefonlarını listele", "musteri_listesi", (r) => r.alan === "telefon");
U("Ahmet'in adresi ne", "musteri_bilgi", (r) => r.alan === "adres" && r.musteriler[0].id === "MST-1");
U("ahmete nasıl ulaşırım", "musteri_bilgi", (r) => r.alan === "telefon");
U("Ayşe Demir'in telefon numarası", "musteri_bilgi", (r) => r.alan === "telefon" && r.musteriler.length === 1);
U("güneş enerji firmasının mail adresi", "musteri_bilgi", (r) => r.musteriler[0].id === "MST-3" && r.alan === "eposta");
U("adanadaki müşteriler", "musteri_listesi", (r) => r.il === "Adana");
U("izmirde kimler var", "musteri_listesi", (r) => r.il === "İzmir");
U("müşteri listesini göster", "musteri_listesi");
U("onay bekleyen başvurular", "basvurular");
U("Şu an kaç cihaz arızalı?", "ariza");
U("bozuk cihazlar hangileri", "ariza");
U("Hangi partide arıza yoğunluğu var?", "parti");
U("Garantisi yakında dolan cihazlar", "garanti");
U("Depoda kaç ürün var?", "depo");
U("sevkteki ürünler", "depo");
U("açık destek talepleri", "talepler");
U("AKU-D24-0071 ne durumda", "cihaz");
U("Genel durumu özetle", "ozet");
U("bugünkü toplam üretim kaç kwh", "inverter");
U("selam naber", null);
U("nasılsın", null);
U("LiFePO4 hücre dengeleme nasıl çalışır?", null);
U("Arıza nasıl tespit edilir?", null);
U("LiFePO4 ile NMC arasındaki fark nedir", null);
U("IEC 62619 standardını anlat", null);
U("bana bir fıkra anlat", null);
console.log("── MÜŞTERİ");
U("ya üretim değilde sohbet etmek isityom dayı ya", null);
U("yok bunalrı değğil", null);
U("yok bunları değil", null);
U("muhabbet edelim mi", null);
U("biraz konuşalım", null);
U("üretim raporunu istemiyorum", null);
U("garantisi biten cihazlar var mı değil mi", "garanti");
U("Ahmet değil Ayşe'nin adresi", "musteri_bilgi");
U("bugünkü üretim ne", "inverter");
U("geçmiş akü sağlık verisi göster", "saglik_gecmisi", (r) => r.gun === 30);
U("akülerin sağlık geçmişi", "saglik_gecmisi");
U("son 3 ayda SOH nasıl değişti", "saglik_gecmisi", (r) => r.gun >= 89 && r.gun <= 92 || r.gun === 90);
U("bu hafta aküler kötüleşti mi", "saglik_gecmisi", (r) => r.gun === 7 || r.gun <= 8);
U("hücre dengesi zamanla nasıl gidiyor", "saglik_gecmisi");
U("AKU-D24-0071 sağlık geçmişi", "cihaz_gecmis", (r) => r.kod === "AKU-D24-0071" && r.gun === 30);
U("AKU-D24-0071 son 2 haftada nasıl değişti", "cihaz_gecmis", (r) => r.gun === 14 || r.gun === 15);
U("AKU-D24-0071", "cihaz");
U("Ahmet'in akü sağlık geçmişi", "saglik_gecmisi", (r) => r.musteriler.length === 1);
U("aküler değil sohbet edelim", null);
U("akü sağlığı nedir", null);
U("arızalı aküler", "ariza");
const Mu = (s, b) => dene(musteriNiyeti, s, b);
Mu("akümün sağlık geçmişini göster", "saglik_gecmisi");
Mu("aküm zamanla yıpranıyor mu", "saglik_gecmisi");
Mu("akümün sağlığı son bir ayda nasıl değişti", "saglik_gecmisi");
Mu("akü ömrü zamanla neden azalır", null);
Mu("akümde ne kadar enerji var", "sarj");
Mu("sistemim değil sohbet etmek istiyorum", null);
Mu("akümde ne kadar enerji var değil mi", "sarj");
Mu("Sistemim nasıl?", "durum");
Mu("Akümde ne kadar enerji var?", "sarj");
Mu("akümün şarjı kaç", "sarj");
Mu("Bugün ne kadar ürettim?", "uretim");
Mu("panelim bu hafta kaç kwh üretti", "uretim");
Mu("Garantim ne zaman bitiyor?", "garanti");
Mu("Destek talebim ne durumda?", "talep");
Mu("akü sıcaklığım kaç derece", "sicaklik");
Mu("cihazlarım neler", "cihazlar");
Mu("sorun var mı sistemde", "durum");
Mu("Akümün ömrünü nasıl uzatırım?", null);
Mu("akü kışın nasıl korunur", null);
Mu("güneş paneli nasıl temizlenir", null);
Mu("selam", null);
Mu("nasılsın dostum", null);
Mu("elektrik faturamı nasıl düşürürüm", null);
console.log("── ZAMAN");
const z = zamanAraligi("12.10.2026 tarihinde kayıt olanlar", new Date(2026, 9, 20)); console.log(z.ad, z.bas.toISOString().slice(0, 10));
console.log(sadelestir("İSTANBUL'daki Şükrü ÇAĞLAR"));
console.log(hata ? `\n${hata} HATA` : "\nHEPSİ TAMAM"); process.exit(hata ? 1 : 0);
